###

GET http://localhost:3000/comments/postComments/67310669e54ac50b7beee619
Content-Type: application/json

###

GET http://localhost:3000/comments/6745c2ddc5e6479dc82b8cb9

###

POST http://localhost:3000/comments/post/67310669e54ac50b7beee619
Content-Type: application/json

{
    "author": "Yoni12345",
    "content": "happy comment"
}


###

PUT http://localhost:3000/comments/6745c2ddc5e6479dc82b8cb9
Content-Type: application/json

{
    "content": "hey, this is my edited comment"
}

###

DELETE http://localhost:3000/comments/6745c2ddc5e6479dc82b8cb9

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "First Post!!!",
    "content": "This is the content of the first post",
    "author": "12345"
}

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/6745c378e7c0d5804f5278ce

###

GET http://localhost:3000/posts?sender=12345

###

PUT http://localhost:3000/posts/6745c378e7c0d5804f5278ce
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content of the post",
    "author": "123456"
}
