###

GET http://localhost:3000/comments/postComments/67310669e54ac50b7beee619
Content-Type: application/json

###

GET http://localhost:3000/comments/673a23072c01a63c16b23be6

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "author": "Yoni",
    "content": "fdsfsd",
    "postId": "67310669e54ac50b7beee619"
}


###

PUT http://localhost:3000/comments/673a23072c01a63c16b23be6
Content-Type: application/json

{
    "content": "hey, this is my second comment"
}

###

DELETE http://localhost:3000/comments/673a5c09be4940984f1080d9

###

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "First Post",
    "content": "This is the content of the first post",
    "owner": "12345"
}

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/673b4bdf40897a580d6183b8

###

GET http://localhost:3000/posts?sender=12345

###

PUT http://localhost:3000/posts/673b4bdf40897a580d6183b8
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content of the post",
    "owner": "12345"
}
